spring:
  application:
    name: "gatewayserver"
#  profiles:             we do not want profiles as for all environments gateway will work in same manner
#    active: "prod"
  config:                                 # to connect to config server and load configurations during startup
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:                              # With this i am telling the gateway to connect to discovery server and locate all deatils of all microservices
      discovery:                          # using which i will allocate all traffic to individual microservices
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true       # enable gateway related proprties inside actuator
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:                                                            # Too enable logging in Gateway server
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

